# -*- coding: utf-8 -*-
from . import chatroom_meta_mixin
from . import res_config_settings
from . import res_partner
from . import chatroom_whatsapp_number
from . import chatroom_tag
from . import chatroom_cart_line
from . import chatroom_channel
from . import chatroom_channel_stage
from . import chatroom_kpi_definition
from . import chatroom_kpi_snapshot
from . import chatroom_kpi_target
from . import chatroom_dashboard_widget
from . import chatroom_dashboard_profile
from . import chatroom_audit_log
from . import chatroom_dashboard_report
from . import chatroom_message
from . import chatroom_scheduled_message
from . import chatroom_template
from . import chatroom_template_variable
from . import chatroom_send_template_wizard
from . import chatroom_send_catalog_wizard
from . import chatroom_new_conversation_wizard
from . import chatroom_reassign_wizard
from . import chatroom_assignment_log
from . import chatroom_canned_response
from . import chatroom_onboarding_wizard
