{
    'name': 'Chatroom Payment: PayPhone Connector',
    'author': 'Bryan Cando',
    'website': 'https://github.com/brphoto/Prueba_Odoo',
    'version': '19.0.1.0.0',
    'category': 'Sales/Payment',
    'summary': 'Use PayPhone links from Chatroom',
    'depends': ['chatroom_payment', 'payment_payphone', 'sale', 'account'],
    'data': [],
    'license': 'LGPL-3',
    'icon': '/chatroom_payment_payphone/static/description/icon.svg',
    'installable': True,
    'application': False,
    'auto_install': True,
}
